### ISSUE TITLE
Template hangs on middle of processing on Google Chrome Dev channel

### ISSUE THREAD

**Issue by jcppkkk** [template-extension/template-chrome#221]
- It hangs during progressing the progress bar. 
- It stops at same point every time
- all templates perform same behavior.
- I tried to enable debugging mode from template setting page, but nothing be logged in devtool console.
- This problem only happened on my PC but not on my NB or other people around, so it should be a rare case.

Maybe there are more things i can do to debug this?

![image](https://cloud.githubusercontent.com/assets/84070/8185560/bbff4190-1477-11e5-92f6-b38049bebf8f.png)
![image](https://cloud.githubusercontent.com/assets/84070/8185561/bdbe0052-1477-11e5-8ad3-e346372c9afe.png)

**Comment by jcppkkk** [comment]
Hi, 
I found the problem is on chrome Dev Channel **45.0.*.0 dev-m (64-bit).**
After i install stable channel **45.0.2431.0 m (64-bit)** i can generate URL again.

**Comment by neocotic** [comment]
Hi @jcppkkk, thanks for reporting this issue. I've never had much luck testing extensions on the unstable channels of Chrome.

I used to think that because it broke on the unstable channels that it would break when those versions were released into the stable channel but that never seemed to happen. The problems were always with changes to Chrome itself that seemed to be fixed before the stable release. For this reason I only support the stable channel.

I'm not sure why you were unable to see anything logged via the devtools. Did you follow the instructions under the "How can I view the logs?" section of the Developer Tools dialog on the options page?

I'm going mark this issue as closed for now since there's no problem in the stable channel.
